### PR TITLE
Fix editable install with pip

### PR DESCRIPTION
**Pull request by oleksis**
Avoid import `textual_astview` when use editable installation using `pip`
```bash
python -m pip install -e .
Obtaining file:///home/oleksis/PYTHON/textual-astview
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/oleksis/PYTHON/textual-astview/setup.py", line 10, in <module>
          import textual_astview
        File "/home/oleksis/PYTHON/textual-astview/textual_astview/__init__.py", line 15, in <module>
          from .widgets.astview     import ASTView, ASTNode
        File "/home/oleksis/PYTHON/textual-astview/textual_astview/widgets/astview.py", line 12, in <module>
          from rich.text import Text
      ModuleNotFoundError: No module named 'rich'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
```

### CODE REVIEW

**Comment by davep** [comment]
Thanks. I'll hold off on this for the moment because I've been meaning to get out of my `setup.py` habit anyway, and this is the repo where I want to look at more current options -- one of my little midwinter holiday side-quests I have lined up. :-)

**Comment by davep** [comment]
Thanks again; this was the push I needed to finally start to break the `setup.cfg` habit. Testing here, with https://github.com/davep/textual-astview/commit/b7777cb3e3b755b8d1bbe034ae49d7da210c0673 in place, editable install works fine.

**Comment by oleksis** [comment]
Ok! You can keep move from `setup.cfg` to `pyproject.toml`

**Comment by davep** [comment]
Aye, that'll be the next logical step.

**Pull request closed without merging**
